# Build stage
FROM golang:1.24-alpine AS builder

WORKDIR /app

# Install git and other dependencies if needed (alpine specific)
RUN apk add --no-cache git

# Copy go mod and sum files
COPY go.mod go.sum ./

# Download all dependencies. Dependencies will be cached if the go.mod and go.sum files are not changed
RUN go mod download

# Copy the source from the current directory to the Working Directory inside the container
COPY . .

# Build the Go app
RUN CGO_ENABLED=0 GOOS=linux go build -o worker ./cmd/worker/main.go

# Run stage
FROM alpine:latest

WORKDIR /app

# Add certificates for HTTPS connections (if needed)
RUN apk --no-cache add ca-certificates

# Copy the Pre-built binary file from the previous stage
COPY --from=builder /app/worker .
COPY --from=builder /app/.env .
COPY --from=builder /app/config ./config

# Command to run the executable
CMD ["./worker"]
